config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'projects', to: 'projects#index'
  get 'projects/:id', to: 'projects#show', as: :project
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many_attached :photos
    validates :title, :description, :technologies, :creation_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      @projects = Project.all
    end

    def show
      @project = Project.find(params[:id])
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% @projects.each do |project| %>
<p><%= project.title %></p>
<% end %>

app/views/projects/index.html.erb
<h1>My projects</h1>

<% @projects.each do |project|  %>
<p><%= link_to project.title, project_path(project) %></p>
<p><% project.technologies.each do |technology| %></p>
<p><%= technology %></p>
<%end  %>
<%end  %>

app/views/projects/show.html.erb
<h2><%= @project.title %></h2>
<p><%= @project.description %></p>
<%= link_to 'Retour aux projets', projects_path %>
<%= cl_image_tag("gHAdqx44jaPxsWZtwfx78bqa", width: 400, height: 300, crop: :fill) %>